### ISSUE TITLE
Headers not defined on upload 

### ISSUE THREAD

**Issue by Tynopia** [neet/masto.js#1076]
Hello, I'm encountering an error when trying to upload a status with an image.
This is a standard NodeJS application, not a browser-based one.

```typescript
        const masto = createRestAPIClient({
            url: "https://mastodon.social",
            accessToken: "..."
        })

        const attachment = await masto.v2.media.create({
            file: new Blob([readFileSync("...")]),
            description: "..."
        })

        await masto.v1.statuses.create({
            status: "...",
            visibility: "public",
            mediaIds: [attachment.id]
        })
```

![image](https://github.com/neet/masto.js/assets/65678882/14d01082-ce4c-4295-ba64-779985b40fb7)

**Comment by neet** [comment]
Hi @Tynopia, thank you for posting an issue. Can you tell me which version of Node.js are you using?

Headers and other APIs from the WHATWG Fetch standard should be implemented all versions of Node.js older than v18.

**Comment by Tynopia** [comment]
Oh, that was a quick reply, thank you!
I'm currently utilizing Node.js 16.x within a FiveM Server environment.

Unfortunately, they haven't been updating the version, and I don't have the opportunity to do so myself.

You can find more information about using Node.js 16.x in FiveM [here](https://docs.fivem.net/docs/scripting-manual/runtimes/javascript/#using-nodejs-apis).

**Comment by neet** [comment]
Hi @Tynopia, thank you for elaborating your environment.

I'm so sorry to say, but Masto.js doesn't support Node.js 16.x anymore as it is really complicated to support both browser environment and Node.js v16 at the same time (due to the lacking `Headers` issue you mentioned).

The Node.js team themselves also decided to end an active support for v16 at the last October (c.f. [endoflife.date](https://endoflife.date/nodejs)) so I believe it's pretty reasonable.

I'm closing this issue for the reasons above, but if you still you still have a problem, please feel free to reopen it.
