### ISSUE TITLE
Make `Status` Public

### ISSUE THREAD

**Issue by fishcharlie** [neet/masto.js#1249]
When I download masto from NPM the `dist/index.d.ts` file has the Status interface but it's not exported. I see in the source code that it is exported tho. I'm not quite sure what the discrepancy is, but it would be super useful to have this exported in the final build on NPM.

**Comment by shuuji3** [comment]
Hi, `masto` doesn't expose `Status` directly, but it can be accessed via `mastodon` type, exported by `index.d.ts` (ref. https://www.unpkg.com/browse/masto@6.10.1/dist/index.d.ts#:~:text=createOAuthAPIClient%2C%20createRestAPIClient%2C%20createStreamingAPIClient%2C-,mastodon,-%7D%3B). So you can refer the `Status` via `mastodon.v1.Status`.

Example usage can be found here:
https://github.com/neet/masto.js/blob/6f93515fd628d37e3faf2a919a423d212085a175/examples/create-new-status.ts#L8

**Comment by neet** [comment]
As @shuuji3 pointed out, `Status` is exported under the `mastodon.v1` namespace. This is because some entity has different types depending on the API version (e.g. `mastodon.v1.Filter` and `mastodon.v2.Filter`). I'm planning improve developer ergonomics, as well as the documentation in the future release!
