### ISSUE TITLE
Some functions seem to be missing in the doc.

### ISSUE THREAD

**Issue by dzx-dzx** [neet/masto.js#391]
Such as `fetchAccountStatuses`.
While "public" functions like `getStatusesIterable` are not accessible at all.

**Comment by neet** [comment]
Hi @dzx-dzx , thank you for your report!

`fetchAccountStatuses` was originally a method from `Masto` class, but since the `Masto` class become too large, I segregated the methods into sub-classes as of `v4.0.0` and now it has renamed to `getStatusesIterable` 

You can access the renamed one via

```ts
import { login } from 'masto';

const main = async () => {
  const masto    = await login(/* ... */);

  // single page
  const statuses = await masto.accounts.getStatusesIterable('76721').next();

  // multiple pages by for-loop
  for await (const statuses of masto.accounts.getStatusesIterable('76721')) {
    if (statuses.length >= 0) break;
  }
}
```

I hope this helps.
