### ISSUE TITLE
Struggling with search

### ISSUE THREAD

**Issue by nhoizey** [neet/masto.js#699]
Hi, I'm trying to use `masto.js` to search for toots and post some. I'm currently stuck at the search part, with different results (and errors) depending on the `q` parameter.

I initially wanted to find my own toots containing my site URL:

```javascript
const dotenv = require("dotenv");
const { login } = require("masto");

dotenv.config();

const main = async () => {
  const MastodonClient = await login({
    url: process.env.MASTODON_INSTANCE,
    accessToken: process.env.MASTODON_ACCESS_TOKEN,
  });

  try {
    const search = await MastodonClient.search({
      type: "statuses",
      accountId: `${process.env.MASTODON_ID}`,
      q: "https://nicolas-hoizey.com/",
    });
    if (search) {
      for await (const statuses of search) {
        console.dir(statuses);
      }
    }
  } catch (error) {
    console.dir(error);
  }
};

main();
```

But I get this error:
```
Error [MastoUnprocessableEntityError]: Unprocessable Entity
    at MastoUnprocessableEntityError.MastoError [as constructor] (./node_modules/masto/dist/index.js:176:28)
    at new MastoUnprocessableEntityError (./node_modules/masto/dist/index.js:301:28)
    at createError (./node_modules/masto/dist/index.js:330:20)
    at HttpAxiosImpl.<anonymous> (./node_modules/masto/dist/index.js:2885:31)
    at step (./node_modules/masto/dist/index.js:103:23)
    at Object.throw (./node_modules/masto/dist/index.js:84:53)
    at rejected (./node_modules/masto/dist/index.js:75:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 422,
  description: 'No description provided for this error',
  details: undefined,
  isMastoError: true
}
```

I tried different values for the `q` parameter, with various results or error, and I don't understand the logic, or what I'm doing wrong:

|value of `q`|result|
|------------|------|
|`"a-dumb-string-I-m-sure-it-will-not-find"`|Finds a lot of content but not containing this string|
|`'"a-dumb-string-I-m-sure-it-will-not-find"'`|`Error: Content-Type is not defined`|
|`'"adumbstringImsureitwillnotfind"'`|`Error: Content-Type is not defined`|
|`"adumbstringImsureitwillnotfind"`|`{ accounts: [], statuses: [], hashtags: [] }` 👍|
|`"https://nicolas-hoizey.com/"`|`Error [MastoUnprocessableEntityError]: Unprocessable Entity`|
|`'"https://nicolas-hoizey.com/"'|`Error: Content-Type is not defined`|

Is there something I missed in the docs, that I should use to "prepare" the `q` value for these searches to work?

Thanks! 🙏

**Comment by neet** [comment]
Hi @nhoizey, Thank you for reporting this issue. I looked a little bit into this topic and found a bug in Masto.js which may resolve some of the problems above. It will soon be released as the next version.

However, as for the rest of the errors, I ended up thinking that Mastodon itself has a bug (or non-documented behaviour) in it. Here's my research.

### `Content-Type is not defined`
This was thrown from Masto because the response from the Mastodon instance did not have a Content-Type header. Mastodon seems to return this empty response when they had an unexpected error while parsing the `q` parameter.
<details><summary>The original response looked like this.</summary>
  <img width="743" alt="image" src="https://user-images.githubusercontent.com/19276905/203993692-85418e4c-bfd8-4f46-b1eb-829487b7be9d.png"></details>
This was caused by we didn't encode the URL before sending it to Mastodon. Therefore, it will be fixed in the next release

### `Error [MastoUnprocessableEntityError]: Unprocessable Entity`
I faced this error with a raw request without using Masto.js with the following URL

- https://mastodon.social/api/v2/search?q=https%3A%2F%2Fexample.com

The search form in the Mastodon Web UI always sends requests with `resolve` and `limit`. Indeed if I put these two query parameters, I could get a response from Mastodon properly.

- https://mastodon.social/api/v2/search?q=https%3A%2F%2Fexample.com&resolve=true&limit=5

So, this might be Mastodon's undocumented behaviour (or just a bug). So I'll keep it the same in the next release.

**Comment by nhoizey** [comment]
@neet it looks like we can't search for URLs inside toot contents, so I opened an issue:
- https://github.com/mastodon/mastodon/issues/21619

**Comment by nightpool** [comment]
@neet You shouldn't send the resolve=true parameter unless you want to opt in to requesting the URL from the third party server (and interpreting it as a remote ActivityPub object), I'm not sure it's appropriate for this use-case.

**Comment by nightpool** [comment]
@nhoizey yes, because you've passed a full URL without indicating that you want to allow Mastodon to resolve this URL and make an authenticated HTTP Signatures request for it using your ID.

**Comment by neet** [comment]
Thank you @nightpool for joining on this issue! I misunderstood what `resolve` is. I thought it was something that requests the server to search from federated instances with this query but it makes sense now.

**Comment by nhoizey** [comment]
@nightpool thanks a lot for the details, as @neet I better understand what `resolve` means. 🙏
