### ISSUE TITLE
Allow creating attachment directly from an URL

### ISSUE THREAD

**Issue by nhoizey** [neet/masto.js#710]
It would be easier to add remote images to toots if the `file` option in `mediaAttachments.create()` directly supported an URL:

```javascript
masto.mediaAttachments.create({
  file: 'https://www.example.com/image.jpg',
  description: 'A remote image',
});
```

**Comment by neet** [comment]
I've been thinking on this issue for a long time, but decided to not implement it because of the reasons below

- After Masto.js v6, we started to use `fetch` API to implement the HTTP request. Since then it has become a lot easier to put a blob to the request
  - For instance, if you have an URL you can just `await fetch(URL).then(r => r.blob())`
  - See also: https://github.com/neet/masto.js/blob/e44e6e61bf689c2e2f1586a91be05b34c6f1bf7c/examples/create-new-status-with-image.ts#L17-L19
- In Mastodon API, they accept not only a binary data as an image, but also a [Base 64 string](https://github.com/neet/masto.js/issues/751#issuecomment-1356874389). Because of this, we need to implement an algorithm that checks if the string is an URL or a Base 64.
  - Even if I implement this type of functionality, `/api/v{1,2}/media` would be the only endpoint that uses this logic. I feel it'd be a bit overengineered.

However, it is still welcomed to post any ideas or comments to improve developer experience. I'd also be happy to offer more ergonomic usage. Thank you.
