### ISSUE TITLE
 error TS2304: Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by AxelTerizaki** [neet/masto.js#72]
Hello :)

Thanks for maintaining this module so frequently to keep up with Mastodon's evolution.

I guess this is related to #60 but not sure how.

I'm trying to build a small bot to post images on a Mastodon account. I'm using version 2.4.0 of the module, and when trying to build my script with typescript, I get the error above in clients/masto/params.d.ts

Here's my tsconfig : 

```JSON
{
	"compilerOptions": {
		// Target latest version of ECMAScript.
		"target": "esNext",
		"module": "commonjs",
		// Search under node_modules for non-relative imports.
		"moduleResolution": "node",
		// Enable strictest settings like strictNullChecks & noImplicitAny.
		// true is better but requires a global refactoring.
		"strict": false,
		// Disallow features that require cross-file information for emit.
		"isolatedModules": true,
		// Import non-ES modules as default imports.
		"esModuleInterop": true,
		// Import constants from JSON (locales).
		"resolveJsonModule": true,
		"sourceMap": true,
		"outDir": "dist/",
		"pretty": true,
		"removeComments": true,
		"downlevelIteration": true,
		"listFiles": true,
		"listEmittedFiles": true,
		"noUnusedParameters": true,
		"noUnusedLocals": true
	},
	"include": [
		"src"
	],
}
```

Did I do something wrong? Hope you can help.

**Comment by neet** [comment]
Thanks for your report. It seems you need to update TS to `3.5.x`.

I've just created a [minimal environment for TypeScript](https://github.com/neetbox/masto-minimal-test) to identify the reason for the error and made sure that it works fine with the latest version of TS so please check it.

> I guess this is related to #60 but not sure how.

You're right. The `Omit` thing wasn't originally a built-in feature, but since it's quite commonly used by the community, it has been [added in TypeScript 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/#the-omit-helper-type). So #60 is a change that removing the library's Omit and using built-in one instead.

**Comment by AxelTerizaki** [comment]
Good find, I'm running 3.4.5. I'll upgrade ASAP :)

Sorry for the trouble, I'll close the issue then.

**Comment by neet** [comment]
I also think it's not nice to keep not inform requirements so I'll add some way to users use the proper version of TS (maybe [this](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions)?). However I'm still working on it so please make sure that using `3.5.x` until then 🙏
