### ISSUE TITLE
Correct way to use Paginator with state management frameworks like @tanstack/query

### ISSUE THREAD

**Issue by likidu** [neet/masto.js#848]
First of all, thanks a lot for developing this lib, makes creating Mastodon app so much easier!

My question is what is a good practice to call `Pagniator<Status[]>` with [`@tanstack/query`](https://tanstack.com/query/latest). In `@tanstack/query`, it has [Infinite Queries](https://tanstack.com/query/v4/docs/react/guides/infinite-queries) to enable the **Load More**.

Here is an example I am using to get the trending list:

```ts
const statuses = masto.v1.trends.listStatuses({ limit: 3 });

const query = createInfiniteQuery({
  queryKey: ['trending'],
  queryFn: async ({ pageParam }) => {
    if (pageParam === undefined) await statuses;
    return await statuses.next();
  },
  getNextPageParam: (lastStatus) => {
    const { done } = lastStatus;
    return !done;
  },
});
```

In this case, if the `done` from latest item of `Pagniator<Status[]>` returns `false`, I can get the next list of `Pagniator<Status[]>` by using `statuses.next()`, which I can trigger it via **Load More**.

In this case, will the response of first `await status` be identical to `await status.next()`? From this issue: https://github.com/neet/masto.js/issues/775#issuecomment-1368024640, it seems the answer is yes?

Or, I can get the status id from the last `Status`, and pass it to the next query as the [`maxId`](https://neet.github.io/masto.js/interfaces/mastodon.v1.ListTimelineParams.html#maxId), which I can also **Load More** which the id is older than this maxId:

```ts
const getStatuses = async (pageParam: string): Promise<mastodon.v1.Status[]> =>
  await masto.v1.trends.listStatuses({
    limit: 3,
    ...(pageParam && { maxId: pageParam }),
  });

const query = createInfiniteQuery({
  queryKey: [queryKey],
  queryFn: ({ pageParam }) => getStatuses(pageParam),
  getNextPageParam: (lastStatuses) => lastStatuses[lastStatuses.length - 1].id,
});
```

Which is the recommended way to use the Paginator?

**Comment by neet** [comment]
Unfortunately, I'm not familiar with @tanstack/query.

I took a bit look into the @tanstack/query documentation, and my thoughts for this is that we don't need to specify anything for `pageParam` because `Paginator` undertakes parameters needed for pagination for you.

Also, you'll probably need to wrap the initialisation part of the paginator by `useMemo` because it stores the parameters for pagination in its internal properties.

> will the response of first await status be identical to await status.next()?

You're right. Basically `await paginator` is an alias for `await paginator.next()`. In addition, it unwraps `value` and drops `done`. I'm offering a method for both one-shot requests and multiple requests because `paginator.next` is just unintuitive for those who don't want multiple pages.

You can take a look at the implementation here:
https://github.com/neet/masto.js/blob/18dd414d3241bbd9a3982fee806091052bd97063/src/paginator.ts#L61

> I can get the status id from the last Status, and pass it to the next query as the [maxId](https://neet.github.io/masto.js/interfaces/mastodon.v1.ListTimelineParams.html#maxId)

I believe that `maxId` tells the server to return statuses that are older than or equal to the `maxId`, which means they include a status that is specified to `maxId`. Therefore you may have a duplicated status.

Mastodon API returns the very first item of the next page in the `Link` response header, but you need some regexp to pick the ID part from the header, and this is why I'm providing an abstract layer named Paginator. 
I believe that `maxId` tells the server to return statuses that are older than or equal to the `maxId`, which means they include a status that is specified to `maxId`. Therefore you may have a duplicated status.

Mastodon API returns the very first item of the next page in the [`Link` response header](https://docs.joinmastodon.org/api/guidelines/#pagination), but you need some regexp to pick the ID part from the header, and this is why I'm providing an abstract layer named Paginator.

**Comment by likidu** [comment]
Thanks @neet for your prompt answers! Now it's more clear for me. Basically like you mentioned, I can just trigger `paginator.next()` until the `done` returns true which means it reaches to the end of the status list.
