### ISSUE TITLE
Make types export

### ISSUE THREAD

**Issue by D4sK43nguru** [neet/masto.js#942]
Currently the typings aren't being exported. When using ``useState()`` in React.js with i.e. the ``masto.v1.status.create()`` function, it'd be useful to be able to set the type for the state, since the async function not always works directly as default value for the state.

Thus, the state gets assigned the type ``any`` from React. With the additional type, the state'd still be assigned the type ``undefined``, but this is solvable with just an if-check. The ``any``-type however is not easy to solve as a developer, other than copying the ``.d.ts`` file and exporting the types.

Edit: Typo

**Comment by neet** [comment]
Hi @D4sK43nguru, thank you for posting an issue.

I could not comprehend the problem that you're facing, can you elaborate on what you mean by *export*? With the latest version 5.11.4, I could verify that it provides proper type information, regardless uses of React or other frameworks.

<img width="962" alt="image" src="https://github.com/neet/masto.js/assets/19276905/4e94b059-65af-49ce-842d-3a9dce5a3ec4">

(Using [Twoslash query comments](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-twoslash-queries))

I'd like to see your minimal reproducible example, or working code if you don't mind. Otherwise, offering exact versions of your environment including package manager, TypeScript, or Node.js may help resolve this problem sooner.

**Comment by D4sK43nguru** [comment]
```TypeScript
import React, { useState } from 'react';
import { login } from 'masto';
import { MASTODON_ACCESS_TOKEN, MASTODON_SOCIAL } from '../utils/constants/token';

const App = () => {
    const [masto, setMasto] = useState();
    const [status, setStatus] = useState();
    useEffect(() => {
        async function getData() {
            const aMasto = await login({ url: MASTODON_SOCIAL, accessToken: MASTODON_ACCESS_TOKEN });
            setMasto(aMasto);
            const aStatus = await masto.v1.statuses.create({
                status: 'Hello from #mastojs\n https://example.com',
                visibility: 'unlisted'
            });
            setStatus(aStatus);
        }

        void getData();
    }, []);

    return <div dangerouslySetInnerHTML={{ __html: status?.content}} />
};

export default App;
```
This would be a good minimal example, I'd say. In this case, the State ``status`` get's assigned solely an “undefined” or an “any” type. Thus further usages of these variables showed that i. e. ``status?.content`` is no part of the state ``status``. All attributes of i. e. status or masto in this case become accessible for TS, if I manually assign the type ``Status`` to the useState so that the line looks like this:

```TypeScript
const [status, setStatus] = useState<Status>();
```

The IDE also imports the type ``Status`` from 'masto', but mentions that it is not an exported type and suggests to change it, adding the ``export`` flag.
![image](https://github.com/neet/masto.js/assets/57450375/3bcb97c8-5be8-4885-9f71-5c8af9267473)

Currently this project uses React 18.2.0, masto 5.11.4 and typeScript 5.0.4.

**Comment by neet** [comment]
Thank you for the explanation. As I illustrated in [an example](https://github.com/neet/masto.js/blob/412a046334bad0306254ee28d1032510112768c7/examples/create-new-status.ts#L9), We're segregating all types related to Mastodon into the namespace `mastodon` and letting them have an explicit version in it, due to our design principle. Therefore, the following snippet could be what you're wishing to achieve

```diff
- import { login } from "masto";
+ import { login, mastodon } from "masto";

- const [masto, setMasto] = useState();
- const [status, setStatus] = useState();
+ const [masto, setMasto] = useState<mastodon.Client>();
+ const [status, setStatus] = useState<mastodon.v1.Status>();
```

> The IDE also imports the type Status from 'masto', but mentions that it is not an exported type and suggests to change it, adding the export flag.

I don't catch up with the TS behaviours of every editor, but I'm aware that the current circumstance -- especially the fact that the internal code directly uses types that are not exported for userland -- is not very intuitive and has room for improvement, and planning to ship a fix in DX in the future versions. See also #776.

**Comment by D4sK43nguru** [comment]
Oh, okay! Thank you for your quick responses!
