### ISSUE TITLE
[Bug] ReferenceError: process is not defined (in a Vite app)

### ISSUE THREAD

**Issue by scambier** [neet/masto.js#954]
Hello, I updated the lib from 5.x to 6.0, and can't get it running. As soon as I'm _importing_ (not even calling) something `from 'masto'`, my application crashes at startup with the following error. Masto 5.x works well.

```
app.js:27  ReferenceError: process is not defined
    at node_modules/.pnpm/parse-link-header@2.0.0/node_modules/parse-link-header/index.js (index.js:7:43)
    at __require (chunk-TCQZMY3T.js?v=4e358f50:9:50)
    at index.js:3:29
```

index.js:7:43 points me to [this code from parse-link-header](
https://github.com/thlorenz/parse-link-header/blob/f380d3f99de4a5411b2d7f8da6069bb7529cbf4a/index.js#L7):

```js
const PARSE_LINK_HEADER_MAXLEN = parseInt(process.env.PARSE_LINK_HEADER_MAXLEN) || 2000;
```

For the context, I'm using masto.js in a SvelteKit application, built with Vite, which does not provide a `process.env`; environment variables are accessed with `import.meta.env.*`

**Comment by neet** [comment]
Hi @scambier, thank you for reporting the issue.

As you pointed out, we introduced `parse-link-header` to make the parsing process robust. This issue seems to be related to thlorenz/parse-link-header#31. `parse-link-header` hasn't been updated for years now, so it seems I should consider another library that doesn't depend on Node.js specific behavior or revert it to the original implementation in v5.

**Comment by neet** [comment]
@scambier  I shipped a beta version without `parse-link-header` module so can you verify if it works? You can install it via:

```
npm install masto@6.0.4-rc.1
```

If it fixes the problem in your environment, I will release it as a stable version.

**Comment by neet** [comment]
@scambier Great! Let me know if you find another problem 😀
